# Generated by Django 4.0.2 on 2022-03-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='mobile_no',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
