# Generated by Django 4.0.2 on 2022-03-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userdetails_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_no',
            field=models.CharField(max_length=100),
        ),
    ]
